### ISSUE TITLE
view[0] is not working in 3.2.1

### ISSUE THREAD

**Issue by ziasultan2** [AgoraIO/Agora-Flutter-SDK#432] opened 2021-09-19 14:55 UTC
the code was working fine a few months ago. I tried to use this code yesterday but it's not working

```
  Widget _viewRows() {
    final views = _getRenderViews();
    switch (views.length) {
      case 1:
        return Container(
            child: Column(
          children: <Widget>[_videoView(views[0])],
        ));
      case 2:
        return Container(
            child: Stack(
          children: <Widget>[
            _videoView(views[1]),
            Align(
              alignment: Alignment.topRight,
              child: new Container(
                height: 200.0,
                width: 200.0,
                child: views[0],                                /// this views[0] is not working giving rendering error
              ),
            ),
          ],
        ));

      case 3:
        return Container(
            child: Column(
          children: <Widget>[
            _expandedVideoRow(views.sublist(0, 2)),
            _expandedVideoRow(views.sublist(2, 3))
          ],
        ));
      case 4:
        return Container(
            child: Column(
          children: <Widget>[
            _expandedVideoRow(views.sublist(0, 2)),
            _expandedVideoRow(views.sublist(2, 4))
          ],
        ));
      default:
    }
    return Container();
  }

  ```

The error I'm getting
```
flutter: The following assertion was thrown while applying parent data.:
flutter: Incorrect use of ParentDataWidget.
flutter: The ParentDataWidget Expanded(flex: 1) wants to apply ParentData of type FlexParentData to a
flutter: RenderObject, which has been set up to accept ParentData of incompatible type StackParentData.
flutter: Usually, this means that the Expanded widget has the wrong ancestor RenderObjectWidget. Typically,
flutter: Expanded widgets are placed directly inside Flex widgets.
flutter: The offending Expanded is currently placed inside a Stack widget.
flutter: The ownership chain for the RenderObject that received the incompatible parent data was:
flutter:   _GestureSemantics ← RawGestureDetector ← GestureDetector ← SurfaceView ← Container ← Expanded ←
flutter: Stack ← Container ← Stack ← Center ← ⋯
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      RenderObjectElement._updateParentData.<anonymous closure> (package:flutter/src/widgets/framework.dart:5689:11)
flutter: #1      RenderObjectElement._updateParentData (package:flutter/src/widgets/framework.dart:5705:6)
flutter: #2      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:5726:7)
flutter: #3      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5420:5)
flutter: #4      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5873:11)
flutter: ...     Normal element mounting (35 frames)
flutter: #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
flutter: #40     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5991:32)
flutter: #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
flutter: #42     Element.updateChild (package:flutter/src/widgets/framework.dart:3255:20)
flutter: #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
flutter: #44     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
flutter: #45     StatelessElement.update (package:flutter/src/widgets/framework.dart:4627:5)
flutter: #46     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
flutter: #47     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5566:32)
flutter: #48     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6001:17)
flutter: #49     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
flutter: #50     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5881:14)
flutter: #51     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
flutter: #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
flutter: #53     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
flutter: #54     StatelessElement.update (package:flutter/src/widgets/framework.dart:4627:5)
flutter: #55     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
flutter: #56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
flutter: #57     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
flutter: #58     ProxyElement.update (package:flutter/src/widgets/framework.dart:4906:5)
flutter: #59     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
flutter: #60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
flutter: #61     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
flutter: #62     ProxyElement.update (package:flutter/src/widgets/framework.dart:4906:5)
flutter: #63     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
flutter: #64     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5566:32)
flutter: #65     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6001:17)
flutter: #66     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
flutter: #67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
flutter: #68     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
flutter: #69     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
flutter: #70     StatefulElement.update (package:flutter/src/widgets/framework.dart:4751:5)
flutter: #71     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
flutter: #72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
flutter: #73     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
flutter: #74     ProxyElement.update (package:flutter/src/widgets/framework.dart:4906:5)
flutter: #75     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
flutter: #76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
flutter: #77     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
flutter: #78     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
flutter: #79     StatefulElement.update (package:flutter/src/widgets/framework.dart:4751:5)
flutter: #80     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
flutter: #81     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5881:14)
flutter: #82     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
flutter: #83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
flutter: #84     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
flutter: #85     StatelessElement.update (package:flutter/src/widgets/framework.dart:4627:5)
flutter: #86     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
flutter: #87     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5881:14)
flutter: #88     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
flutter: #89     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
flutter: #90     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
flutter: #91     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
flutter: #92     StatefulElement.update (package:flutter/src/widgets/framework.dart:4751:5)
flutter: #93     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
flutter: #94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
flutter: #95     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
flutter: #96     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
flutter: #97     StatefulElement.update (package:flutter/src/widgets/framework.dart:4751:5)
flutter: #98     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
flutter: #99     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
flutter: #100    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
flutter: #101    ProxyElement.update (package:flutter/src/widgets/framework.dart:4906:5)
flutter: #102    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
flutter: #103    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
flutter: #104    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
flutter: #105    ProxyElement.update (package:flutter/src/widgets/framework.dart:4906:5)
flutter: #106    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
flutter: #107    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
flutter: #108    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
flutter: #109    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
flutter: #110    StatefulElement.update (package:flutter/src/widgets/framework.dart:4751:5)
flutter: #111    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
flutter: #112    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
flutter: #113    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
flutter: #114    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
flutter: #115    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:33)
flutter: #116    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:866:20)
flutter: #117    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
flutter: #118    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
flutter: #119    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1056:9)
flutter: #120    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:972:5)
flutter: #124    _invoke (dart:ui/hooks.dart:253:10)
flutter: #125    _drawFrame (dart:ui/hooks.dart:211:3)
flutter: (elided 3 frames from dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: Incorrect use of ParentDataWidget.
```

**Comment by LichKing-2234** [comment] 2021-09-22 02:46
duplicate of https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart/issues/239

**Closed by LichKing-2234** 2021-09-22 02:46 UTC
