### ISSUE TITLE
Event activeSpeaker is not represent uid local user

### ISSUE THREAD

**Issue by drunamana** [AgoraIO/Agora-Flutter-SDK#431] opened 2021-09-17 14:40 UTC
With representing remote uid all ok. Using mode with video. By documentation:

The UidCallback typedef includes the following parameters:
int uid: User ID of the active speaker. A uid of 0 represents the local user.

version agora_rtc_engine: 4.0.7

**Comment by LichKing-2234** [comment] 2021-09-18 06:28
duplicate of  #150

**Closed by LichKing-2234** 2021-09-18 06:28 UTC
