### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method joinChannel on channel agora_rtc_engine)

### ISSUE THREAD

**Issue by ebrahimimasod** [AgoraIO/Agora-Flutter-SDK#253] opened 2021-02-05 06:45 UTC
I use :
 agora_rtc_engine: ^3.1.3

error : 
E/flutter (16307): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method joinChannel on channel agora_rtc_engine)
E/flutter (16307): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter (16307): <asynchronous suspension>
E/flutter (16307): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (16307): #2      RtcEngine._invokeMethod (package:agora_rtc_engine/src/rtc_engine.dart:35:27)
E/flutter (16307): #3      RtcEngine.joinChannel (package:agora_rtc_engine/src/rtc_engine.dart:126:12)
E/flutter (16307): #4      _VideoCallPageState.initialize (package:telegram/pages/VideoCallPage.dart:72:19)
E/flutter (16307): <asynchronous suspension>

**Comment by LichKing-2234** [comment] 2021-02-07 03:20
have you tried our example or quickstart?

**Comment by ebrahimimasod** [comment] 2021-02-07 10:23
Yes I use quickstart project in github

**Comment by LichKing-2234** [comment] 2021-02-12 03:07
maybe you open `.xcodeproj`, you should open `.xcworkspace`

**Comment by LichKing-2234** [comment] 2021-04-08 08:14
I will close this issue, you can reopen it if the issue still exists.

**Closed by LichKing-2234** 2021-04-08 08:14 UTC

**Comment by alenpmla** [comment] 2021-06-26 09:42
I am facing this issue on the latest agora SDK. I had tried all the solutions mentioned here. 

`V/FA      (  391): Inactivity, disconnecting from the service
W/System.err(  391): java.lang.reflect.InvocationTargetException
W/System.err(  391): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(  391): 	at io.agora.agora_rtc_engine.AgoraRtcEnginePlugin.onMethodCall(AgoraRtcEnginePlugin.kt:113)
W/System.err(  391): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
W/System.err(  391): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
W/System.err(  391): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
W/System.err(  391): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(  391): 	at android.os.MessageQueue.next(MessageQueue.java:335)
W/System.err(  391): 	at android.os.Looper.loop(Looper.java:206)
W/System.err(  391): 	at android.app.ActivityThread.main(ActivityThread.java:8506)
W/System.err(  391): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(  391): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
W/System.err(  391): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)
W/System.err(  391): Caused by: kotlin.TypeCastException: null cannot be cast to non-null type kotlin.Number
W/System.err(  391): 	at io.agora.rtc.base.RtcEngineManager.joinChannel(RtcEngine.kt:398)
W/System.err(  391): 	... 12 more
E/flutter (  391): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method joinChannel on channel agora_rtc_engine)
E/flutter (  391): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)`

**Comment by MasoomRaza752** [comment] 2022-01-24 05:01
when i use agora 4.2.0 it did not allow my app to install and crash it by giving the error.'Flutter initialization failed' and i'm using the flutter 2.8.1
