### ISSUE TITLE
AudioOutputRoutingEnumMap with value of 9 throws Flutter Exception

### ISSUE THREAD

**Issue by ChrisMICDUP** [AgoraIO/Agora-Flutter-SDK#582] opened 2022-02-08 04:07 UTC
My app experiences an unknown Flutter Exception with  agora_rtc_engine v4.2.0

Non-fatal Exception: FlutterError
Invalid argument(s): `9` is not one of the supported values: -1, 0, 1, 2, 3, 4, 5. Error thrown null.
Non-fatal Exception: FlutterError
0  ???                            0x0 (null).$enumDecode + 83 (enum_helpers.dart:83)
1  ???                            0x0 new EnumConverter.fromValue + 14 (enum_converter.dart:14)
2  ???                            0x0 new AudioOutputRoutingConverter.fromValue + 141 (enum_converter.dart:141)
3  ???                            0x0 RtcEngineEventHandler.process + 1303 (events.dart:1303)
4  ???                            0x0 RtcEngine.setEventHandler.<fn> + 187 (rtc_engine.dart:187)

**To Reproduce**
Unclear, User joined Agora channel as audience

**Expected behaviour**
Be nice to know what the event is...

**Smartphone (please complete the following information):**
iOS 15.2.1
iPhone 11 Pro

**Additional context**
Agora channel with two broadcasters had already started. This particular user does not have a fantastic internet connection.

**Comment by littleGnAl** [comment] 2022-02-08 04:30
@ChrisMICDUP This bug is from the `audioRouteChanged` event, and the root cause is that we miss the enum definition in `AudioOutputRouting`, the full definition can be found [here](https://docs.agora.io/en/Voice/API%20Reference/oc/Constants/AgoraAudioOutputRouting.html). It will be fixed later.

**Closed** 2022-02-08 07:03 UTC
