### ISSUE TITLE
Android Bluetooth headphones get no sound.

### ISSUE THREAD

**Issue by Aliharu** [AgoraIO/Agora-Flutter-SDK#27] opened 2019-08-15 18:15 UTC
When I use bluetooth wireless headphones with an android device I get no sound.

**Comment by Matrixbirds** [comment] 2019-08-16 05:05
Please provide your devices info and flutter environment here.
I will schedule try to reproduce ASAP.

**Comment by mikebcurtis** [comment] 2019-08-29 20:52
All audio (including audio from other apps) plays through bluetooth headphones until an Agora call starts. We call AgoraRtcEngine.setDefaultAudioRouteToSpeaker(false) and AgoraRtcEngine.setEnableSpeakerphone(false) before joining the call, but as soon as an Agora call starts the audio output switches from bluetooth headphones to speakerphone. When the Agora call ends, audio output switches back to the bluetooth headphones, including audio from other apps.

I put a print statement in the AgoraRtcEngine.onAudioRouteChanged callback and another right after we call AgoraRtcEngine.setEnableSpeakerphone and this is the output:
`
I/flutter (18438):  ---------- setEnableSpeakerphone(false)
I/flutter (18438):  ---------- onAudioRouteChanged: 5 (AUDIO_ROUTE_HEADSETBLUETOOTH)
I/flutter (18438):  ---------- onAudioRouteChanged: 5 (AUDIO_ROUTE_HEADSETBLUETOOTH)
I/flutter (18438):  ---------- setEnableSpeakerphone(true)
I/flutter (18438):  ---------- onAudioRouteChanged: 3 (AUDIO_ROUTE_SPEAKERPHONE)
I/flutter (18438):  ---------- onAudioRouteChanged: 3 (AUDIO_ROUTE_SPEAKERPHONE)
`
However, audio outputs through the speakerphone during the entire audio call, even when onAudioRouteChanged reports 5 (AUDIO_ROUTE_HEADSETBLUETOOTH).

I reproduced the issue on a T-Mobile REVVL (REVVL 5049W) running Android 7.0 and a Samsung Galaxy S8 (SM-G950U) running Android 9

Here is my results from flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G87, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.37.1)
[✓] Connected device (2 available)

• No issues found!

**Comment by Matrixbirds** [comment] 2019-08-30 02:33
Which bluetooth headphones did u used? And Please also provide your headphones bluetooth protocol, you could find it from your android system. @mikebcurtis

**Comment by Matrixbirds** [comment] 2019-08-30 04:06
@mikebcurtis  If you r using communication mode, you could try `setAudioProfile(AudioProfile.SpeechStandard, AudioScenario.ChatRoomEntertainment)`
If you r using live broadcasting mode, you could try `setAudioProfile(AudioProfile.MusicStandard, AudioScenario.ChatRoomEntertainment)`

**Comment by alexsullivan114** [comment] 2020-03-25 14:31
@mikebcurtis or @Aliharu Did either of y'all find a resolution to this? I'm running into the same problem on native Android. The above solution didn't change anything for me.

**Comment by LichKing-2234** [comment] 2020-03-26 12:23
@alexsullivan114 can you hear the voice from speakerphone or handset?

**Comment by alexsullivan114** [comment] 2020-03-26 12:34
@LichKing-2234 Yes. The sound comes out of the earpiece, if I set speakerphone on it comes through the speakerphone and if I have headphones _plugged in_ then it comes through the headphones. But if I have headphones connected via bluetooth it will still come out of the earpiece or speakerphone.

**Comment by LichKing-2234** [comment] 2020-03-26 12:39
@alexsullivan114 you can try `setAudioProfile(AudioProfile.Default, AudioScenario.GameStreaming)`

**Comment by alexsullivan114** [comment] 2020-03-26 12:46
I'll give that a shot

**Comment by alexsullivan114** [comment] 2020-03-26 13:03
@LichKing-2234 Hey it looks like that fixed it! Not sure why but thanks!

**Comment by LichKing-2234** [comment] 2020-03-26 13:18
@alexsullivan114 I think here have some problem, we will check it, but you can use the configuration above before we fixed it

**Comment by thangvq95** [comment] 2020-08-14 12:25
Hey @LichKing-2234, I have same issue with this, config setAudioProfile(AudioProfile.Default, AudioScenario.GameStreaming) will have solve solution but i don't want to use the scenario GameStreaming to my application. Could you please take a look on this. Thanks a lot!

**Comment by LichKing-2234** [comment] 2020-08-16 07:36
@thangvq95 Have you try the dev version? I think it is fixed by native platform.

**Comment by thangvq95** [comment] 2020-08-17 04:03
@LichKing-2234 yeps, i'm using dev version. it's only work for GameStreaming scenario!

**Comment by LichKing-2234** [comment] 2020-08-17 06:07
@thangvq95 I will check later

**Comment by LichKing-2234** [comment] 2020-10-28 03:54
@thangvq95 
you can use `LiveBroadcasting` mode.
```
setChannelProfile(ChannelProfile.LiveBroadcasting);
setClientRole(ClientRole.Broadcaster);
```

**Comment by fareesh** [comment] 2021-05-16 22:46
This seems to be resolved by adding the BLUETOOTH_ADMIN permission. Can anyone try this and confirm?

**Comment by ishdemon** [comment] 2021-07-20 07:32
> @thangvq95
> you can use `LiveBroadcasting` mode.
> 
> ```
> setChannelProfile(ChannelProfile.LiveBroadcasting);
> setClientRole(ClientRole.Broadcaster);
> ```

Issue still occurs even with `LiveBroadcasting` mode.

**Comment by littleGnAl** [comment] 2022-04-21 07:18
Please try `agora_rtc_engine: 5.1.0`.

**Closed** 2022-05-12 09:09 UTC
Labels: bug, waiting for customer response

**Comment by maylorsan** [comment] 2023-03-09 11:22
@silversquall any updates?
We getting same issue on android devices.
